# Generated by Django 3.2.8 on 2021-10-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211024_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scream',
            name='audio_path',
            field=models.FileField(null=True, upload_to='media/audio'),
        ),
        migrations.AlterField(
            model_name='scream',
            name='video_path',
            field=models.FileField(null=True, upload_to='media/images'),
        ),
    ]
