FROM ubuntu:18.04
RUN apt-get update && \
    apt-get install -y \
    vim \
    git \
    sudo \
    curl \
    wget \
    locales \
    python3.8 \
    python3-pip \
    libgl1-mesa-dev \
    portaudio19-dev \
    mecab \
    libmecab-dev \
    mecab-ipadic-utf8 && \
    echo "ja_JP UTF-8" > /etc/locale.gen && \
    git clone https://github.com/neologd/mecab-ipadic-neologd.git && \
    cd mecab-ipadic-neologd && \
    sudo bin/install-mecab-ipadic-neologd -n -y && \
    echo "dicdir=/usr/lib/x86_64-linux-gnu/mecab/dic/mecab-ipadic-neologd">/etc/mecabrc && \
    cp /etc/mecabrc /usr/local/etc/
RUN mkdir /code
COPY requirements.txt /code/
WORKDIR /code
RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt
COPY . /code/